---
# tasks file for apache
  - name: installation httpd
    import_tasks: install_centos.yml
    when: ansible_os_family == "RedHat"
  - name: installation Apache2
    import_tasks: install_ubuntu.yml
    when: ansible_os_family == "Debian"
  - name: configuration httpd
    import_tasks: configure_centos.yml
    when: ansible_os_family == "RedHat"
  - name: configuration Apache2
    import_tasks: configure_ubuntu.yml
    when: ansible_os_family == "Debian"

  - name: deploy index.html
    template: src=index.html.j2 dest=/var/www/html/index.html

  - name: httpd restarted
    systemd: named=httpd state=started enabled=true
    when: ansible_os_family == "RedHat"

  - name: apache stated
    systemd: name=apache2 state=started
    when: ansible_os_family == "Debian"
